### ISSUE TITLE
feature proposal: make slptool invocation details configurable

### ISSUE THREAD

**Issue by mattvonrocketstein** [icanhazbroccoli/ex_slp_tk#1]
Currently there is a hard-coded [module attribute](https://github.com/icanhazbroccoli/ex_slp_tk/blob/master/lib/ex_slp/tool.ex#L3) that controls the invocation of slptool.  (My use-case: I'm running the slpd server from inside docker, and would prefer to invoke slptool similarly).  I'm pretty new to Elixir, but I'm not seeing a clean way to override the module attribute and don't want to monkey patch.  How would you feel about a pull-request that gets `@slptool` from Application configuration?  I'll try it out if you're interested in merging it.

**Comment by icanhazbroccoli** [comment]
@mattvonrocketstein : please go ahead. Sounds reasonable to me.

**Comment by icanhazbroccoli** [comment]
Accepted merge request aee32ac04
The new package version is on [hex.pm](https://hex.pm/packages/ex_slp/0.1.1) now.
Many thanks @mattvonrocketstein
