### ISSUE TITLE
document a practical example

### ISSUE THREAD

**Issue by mattvonrocketstein** [icanhazbroccoli/ex_slp_tk#3]
https://gist.github.com/mattvonrocketstein/580e04631af195edae0c9157f47758fe

**Comment by icanhazbroccoli** [comment]
Implemented an example app in b2f09ca95. Feel free to implement another example(s) under /examples folder and open a pull-request. I believe having them packaged as mix apps make 'em runnable from the box and easier to clone/reuse. Closing the issue for now.
